export type CameraConfigOptions = |
    "syncdatetime" |
    "uilock" |
    "popupflash" |
    "autofocusdrive" |
    "manualfocusdrive" |
    "cancelautofocus" |
    "eoszoom" |
    "eoszoomposition" |
    "viewfinder" |
    "eosremoterelease" |
    "eosmoviemode" |
    "opcode" |
    "datetime" |
    "reviewtime" |
    "output" |
    "movierecordtarget" |
    "evfmode" |
    "ownername" |
    "artist" |
    "copyright" |
    "customfuncex" |
    "focusinfo" |
    "strobofiring" |
    "flashcharged" |
    "autopoweroff" |
    "depthoffield" |
    "capturetarget" |
    "capture" |
    "remotemode" |
    "eventmode" |
    "serialnumber" |
    "manufacturer" |
    "cameramodel" |
    "deviceversion" |
    "vendorextension" |
    "model" |
    "ptpversion" |
    "Battery Level" |
    "batterylevel" |
    "lensname" |
    "eosserialnumber" |
    "shuttercounter" |
    "availableshots" |
    "eosmovieswitch" |
    "imageformat" |
    "imageformatsd" |
    "iso" |
    "whitebalance" |
    "whitebalancexa" |
    "whitebalancexb" |
    "colorspace" |
    "exposurecompensation" |
    "focusmode" |
    "storageid" |
    "autoexposuremode" |
    "drivemode" |
    "picturestyle" |
    "aperture" |
    "shutterspeed" |
    "meteringmode" |
    "liveviewsize" |
    "bracketmode" |
    "aeb" |
    "alomode";
